### ISSUE TITLE
Custom model

### ISSUE THREAD

**Issue by 32177061** [XRLabPomerania/Hololens-2-Object-Detection#1]
Hi @yoKurt94 
I tried this project and it worked well on my hololens.Can I use my custom model? I tried the model I trained in azure Custom Vision, but it didn't work. And why do you need two models (efficientnet-lite4-11 and BlazeFace model) in the project? I'm new to this field, and I'd appreciate it if you could answer me.

**Comment by yoKurt94** [comment]
Hi, the project is supposed to work I´like this: if you want to use BlazeFace, you set the `useBlazeFace` property in the `CustomVisionAnalyzer.cs` to `true`. If you want to use the efficient net model, you set it to `false`, but right now the efficient net model is not working with the project. Should be fixed soon or replaced by another model because it has no bounding box.
If you want to use your own model, you could replace the efficient net model with your model by dragging and dropping your model into the CustomVisionAnalyzer component section of the MainCamera. You then have to modify the preprocessing (i.e. the image size, input and output tensor names etc.) to fit your model. You can use the app Netron to check what input names, output names and tensors have to look like. Alternatively, you could modify all these variables and functions of the BlazeFace Model, which includes a bounding box.
What is you model supposed to do? What are the inputs and outputs?

**Comment by 32177061** [comment]
I trained a model on azure to identify cups. Its input and output are as follows. If I modify the BlazeFace model directly, which variables should I modify? In CustomVisionAnalyzer.cs, the only thing I can confirm that needs to be changed is Figure 2. What else needs to be changed? Thank you very much
![微信截图_20220720062554](https://user-images.githubusercontent.com/63915347/179852278-b57e6553-5b60-4179-92f8-8f45af469acc.png)
![微信截图_20220720062717](https://user-images.githubusercontent.com/63915347/179852322-022b9e8d-31b8-4fac-97ea-1db4bea1c034.png)
!

**Comment by yoKurt94** [comment]
Just for clarity, did you use [this](https://docs.microsoft.com/de-de/windows/mixed-reality/develop/unity/tutorials/mr-azure-310) resource to train your model?

**Comment by 32177061** [comment]
Yes, I used azure Custom Vision to train my model.

**Comment by yoKurt94** [comment]
I will look into your model and come back to you.

**Comment by 32177061** [comment]
Thank you very much![https://drive.google.com/file/d/1H0OiGRq6pNNKEqg4HkqFZGjSzX1TVGV9/view?usp=sharing](url)This is the model I trained. And the picture of the cup
![KakaoTalk_20220713_131016952_17](https://user-images.githubusercontent.com/63915347/179919805-01cd6488-476c-46b1-a4cd-f04887b4aac5.jpg)

**Comment by yoKurt94** [comment]
Adding your model is now very easy. Add it to your Assets/Models folder. Then drag and drop your model into the `Efficient Net Model File` box inside the CustomVisionAnalyzer Script of the Main Camera (which is inside the Hierarchy of the Scene). Then you have to modify the `CustomVisionAnalyzer.cs`: set `useBlazeFace` to `false`, `EFICNET_IMAGE_SIZE` to `416`, `EFICNET_INPUT_NAME` to `data` and `EFICNET_OUTPUT_NAME` to `model_outputs0`. Inside the `RunModelRoutine` function, it will assign the highest value inside the output array to an element of the efficientnet labels, which is of course wrong. Your model's output is just the bounding box of the cup. However, I do not know how to assign the values of your output tensor to the position and size of a  bounding box. Please let me know if you have more information about that.

**Comment by 32177061** [comment]
I found an article about how to run azure custom vision model on unity. Can [it](https://localjoost.github.io/labeling-toy-aircraft-in-3d-space-using/) be combined with existing code?And the existing RayCastHelper.cs doesn't seem to convert coordinates into spatial coordinates?

**Comment by yoKurt94** [comment]
You could combine or integrate it, but as long as you dont know how to interpret your model's output tensor into the bounding box, you wouldn't get any further than you would when you follow my previous comment. The RayCastHelper sends a ray into the direction you specify and returns a raycast hit. The label will then be placed on the surface of hit mesh (inside the world).
